import json
import uuid
from datetime import datetime, timezone

from flask import Flask, jsonify, request
from flask_limiter import Limiter
from flask_limiter.util import get_remote_address

import config
from detect import detect_signal

app = Flask(__name__)

limiter = Limiter(
    get_remote_address,
    app=app,
    default_limits=[],
    storage_uri="memory://",
)

@app.route("/")
def home():
    return "Provenance Guard is running."


def apply_label(score: float) -> dict:
    """Map a confidence score to a transparency label and user-friendly description."""
    LABEL_MAP = [
        (0.90, "high-confidence AI",
        "There is a high likelihood that the text is by an AI. "
        "We estimate that there is roughly 9 in 10 chance of this being AI generated."),
        (0.26, "uncertain",
        "It is difficult to say with high confidence whether the text "
        "is generated by an AI or written by a human."),
        (0.00, "high-confidence human",
        "There is a strong likelihood that the text is by a human. "
        "We estimate that there is a roughly 3 in 4 chance of this being written by a human."),
    ]

    for threshold, label, description in LABEL_MAP:
        if score >= threshold:
            return {"label": label, "user_friendly_description": description}
    return {"label": "uncertain", "user_friendly_description": _LABEL_MAP[1][2]}


def _make_entry(*, content_id, creator_id, status,
                label=None, confidence_score=None, signals=None, message=None):
    return {
        "content_id": content_id,
        "creator_id": creator_id,
        "status": status,
        "label": label,
        "confidence_score": confidence_score,
        "signals": signals,
        "message": message,
    }

@app.route("/submit", methods=["POST"])
@limiter.limit(f"{config.MAX_SUBMISSIONS_IN_TIME_WINDOW} per minute;{config.MAX_SUBMISSIONS_PER_DAY} per day")
def submit():
    """Handle content submission and return a detection result."""
    data = request.get_json()
    content = data.get("content", "")
    creator_id = data.get("creator_id")
    content_id = str(uuid.uuid4())

    # Step 2: length validation
    if len(content) < config.MINIMUM_LENGTH:
        entry = _make_entry(content_id=content_id, creator_id=creator_id, status="error",
                            message="Submitted text is too short to be assessed")
        log_event(entry)
        return jsonify(entry)

    if len(content) > config.MAXIMUM_LENGTH:
        entry = _make_entry(content_id=content_id, creator_id=creator_id, status="error",
                            message="Submitted text is too long to be assessed")
        log_event(entry)
        return jsonify(entry)

    # Step 4: run detection pipeline
    detection = detect_signal(content)
    if detection["message"] is not None:
        entry = _make_entry(content_id=content_id, creator_id=creator_id, status="error",
                            message=detection["message"])
        log_event(entry)
        return jsonify(entry)

    # Step 5: apply label
    label = apply_label(detection["confidence_score"])["label"]

    # Step 6: log and return
    entry = _make_entry(content_id=content_id, creator_id=creator_id, status="scored",
                        label=label,
                        confidence_score=detection["confidence_score"],
                        signals=detection["signals"])
    log_event(entry)
    return jsonify(entry)


@app.route("/appeal", methods=["POST"])
def appeal():
    """Handle content appeal and return a placeholder response."""
    data = request.get_json()
    content_id = data.get("content_id")

    # Update the content's status and log the appeal (see section 6).
    return jsonify({
        "content_id": content_id,
        "status": "under_review",
        "message": "Your appeal was received and is under review.",
    })

def log_event(entry):
    """Log an event to the audit log."""
    entry["timestamp"] = datetime.now(timezone.utc).isoformat()
    with open(config.LOG_FILE, "a") as f:
        f.write(json.dumps(entry) + "\n")

def get_log():
    try:
        with open(config.LOG_FILE) as f:
            return [json.loads(line) for line in f]
    except FileNotFoundError:
        return []


@app.route("/log", methods=["GET"])
def read_log():
    return jsonify({"entries": get_log()})

if __name__ == "__main__":
    app.run(port=5000, debug=True)
