import json
import uuid
from datetime import datetime, timezone

from flask import Flask, jsonify, request
from flask_limiter import Limiter
from flask_limiter.util import get_remote_address

import config
from detect import detect_signal

app = Flask(__name__)

limiter = Limiter(
    get_remote_address,
    app=app,
    default_limits=[],
    storage_uri="memory://",
)

_LABEL_MAP = [
    (0.90, "high-confidence AI",
    "There is a high likelihood that the text is by an AI. "
    "We estimate that there is roughly 9 in 10 chance of this being AI generated."),
    (0.26, "uncertain",
    "It is difficult to say with high confidence whether the text "
    "is generated by an AI or written by a human."),
    (0.00, "high-confidence human",
    "There is a strong likelihood that the text is by a human. "
    "We estimate that there is a roughly 3 in 4 chance of this being written by a human."),
]

@app.route("/")
def home():
    return "Provenance Guard is running."


def apply_label(score: float) -> dict:
    """Map a confidence score to a transparency label and user-friendly description."""

    for threshold, label, description in _LABEL_MAP:
        if score >= threshold:
            return {"label": label, "user_friendly_description": description}
    return {"label": "uncertain", "user_friendly_description": _LABEL_MAP[1][2]}


def _make_entry(*, content_id, creator_id, status,
                label=None, confidence_score=None, signals=None,
                message=None, creator_reasoning=None):
    return {
        "content_id": content_id,
        "creator_id": creator_id,
        "status": status,
        "label": label,
        "confidence_score": confidence_score,
        "signals": signals,
        "message": message,
        "creator_reasoning": creator_reasoning,
    }

@app.route("/submit", methods=["POST"])
@limiter.limit(f"{config.MAX_SUBMISSIONS_IN_TIME_WINDOW} per minute;{config.MAX_SUBMISSIONS_PER_DAY} per day")
def submit():
    """Handle content submission and return a detection result."""
    data = request.get_json()
    text = data.get("text", "")
    creator_id = data.get("creator_id")
    content_id = str(uuid.uuid4())

    # Step 2: length validation
    if len(text) < config.MINIMUM_LENGTH:
        entry = _make_entry(content_id=content_id, creator_id=creator_id, status="error",
                            message="Submitted text is too short to be assessed")
        log_event(entry)
        return jsonify(entry)

    if len(text) > config.MAXIMUM_LENGTH:
        entry = _make_entry(content_id=content_id, creator_id=creator_id, status="error",
                            message="Submitted text is too long to be assessed")
        log_event(entry)
        return jsonify(entry)

    # Step 4: run detection pipeline
    detection = detect_signal(text)
    if detection["message"] is not None:
        entry = _make_entry(content_id=content_id, creator_id=creator_id, status="error",
                            message=detection["message"])
        log_event(entry)
        return jsonify(entry)

    # Step 5: apply label
    label_result = apply_label(detection["confidence_score"])

    # Step 6: log (without description), then return response (with description)
    entry = _make_entry(content_id=content_id, creator_id=creator_id, status="scored",
                        label=label_result["label"],
                        confidence_score=detection["confidence_score"],
                        signals=detection["signals"])
    log_event(entry)
    return jsonify({**entry, "user_friendly_description": label_result["user_friendly_description"]})


@app.route("/appeal", methods=["POST"])
def appeal():
    """Log a creator's appeal against a classification."""
    data = request.get_json()
    try:
        entry = _make_entry(
            content_id=data.get("content_id"),
            creator_id=data.get("creator_id"),
            status="under_review",
            label=data.get("label"),
            confidence_score=data.get("confidence_score"),
            signals=data.get("signals"),
            creator_reasoning=data.get("creator_reasoning"),
        )
        log_event(entry)
        return jsonify({"message": "Appeal received. Content status updated to 'under review'."})
    except Exception:
        return jsonify({"message": "There was an error with your submission. Please try again."})

def log_event(entry):
    """Log an event to the audit log."""
    entry["timestamp"] = datetime.now(timezone.utc).isoformat()
    with open(config.LOG_FILE, "a") as f:
        f.write(json.dumps(entry) + "\n")

def get_log():
    try:
        with open(config.LOG_FILE) as f:
            return [json.loads(line) for line in f if line.strip()]
    except FileNotFoundError:
        return []


@app.route("/log", methods=["GET"])
def read_log():
    return jsonify({"entries": get_log()})

if __name__ == "__main__":
    app.run(port=5001, debug=True)
