import json
import uuid
from datetime import datetime, timezone

from flask import Flask, jsonify, request
from flask_limiter import Limiter
from flask_limiter.util import get_remote_address

import config
from detect import assess_signal_llm

app = Flask(__name__)

limiter = Limiter(
    get_remote_address,
    app=app,
    default_limits=[],
    storage_uri="memory://",
)

@app.route("/")
def home():
    return "Provenance Guard is running."

@app.route("/submit", methods=["POST"])
@limiter.limit(f"{config.MAX_SUBMISSIONS_IN_TIME_WINDOW} per minute;{config.MAX_SUBMISSIONS_PER_DAY} per day")
def submit():
    """Handle content submission and return a detection result."""
    data = request.get_json()
    content = data.get("content", "")
    creator_id = data.get("creator_id")
    content_id = str(uuid.uuid4())

    # Step 2: length validation
    if len(content) < config.MINIMUM_LENGTH:
        entry = _make_entry(content_id=content_id, creator_id=creator_id, status="error",
                            message="Submitted text is too short to be assessed")
        log_event(entry)
        return jsonify(entry)

    if len(content) > config.MAXIMUM_LENGTH:
        entry = _make_entry(content_id=content_id, creator_id=creator_id, status="error",
                            message="Submitted text is too long to be assessed")
        log_event(entry)
        return jsonify(entry)

    # Step 4: LLM signal (#1)
    llm_result = assess_signal_llm(content)
    if llm_result["message"] is not None:
        entry = _make_entry(content_id=content_id, creator_id=creator_id, status="error",
                            message=llm_result["message"])
        log_event(entry)
        return jsonify(entry)

    # Step 5: placeholder confidence + label until M4/M5
    signals = {
        "LLM": llm_result["confidence_score"],
        "LLM_reasoning": llm_result["reasoning"],
        "stylometric": 0.5,  # placeholder until M4
    }
    confidence_score = llm_result["confidence_score"]  # placeholder until M4 averages signals
    label = "uncertain"  # placeholder until M5 implements apply_label()
    user_friendly_description = (
        "It is difficult to say with high confidence whether the text "
        "is generated by an AI or written by a human."
    )

    # Step 6: log and return
    entry = _make_entry(content_id=content_id, creator_id=creator_id, status="scored",
                        label=label,
                        user_friendly_description=user_friendly_description,
                        confidence_score=confidence_score,
                        signals=signals)
    log_event(entry)
    return jsonify(entry)


def _make_entry(*, content_id, creator_id, status,
                label=None, user_friendly_description=None,
                confidence_score=None, signals=None, message=None):
    return {
        "content_id": content_id,
        "creator_id": creator_id,
        "status": status,
        "label": label,
        "confidence_score": confidence_score,
        "signals": signals,
        "message": message,
    }

@app.route("/appeal", methods=["POST"])
def appeal():
    """Handle content appeal and return a placeholder response."""
    data = request.get_json()
    content_id = data.get("content_id")

    # Update the content's status and log the appeal (see section 6).
    return jsonify({
        "content_id": content_id,
        "status": "under_review",
        "message": "Your appeal was received and is under review.",
    })

def log_event(entry):
    """Log an event to the audit log."""
    entry["timestamp"] = datetime.now(timezone.utc).isoformat()
    with open(config.LOG_FILE, "a") as f:
        f.write(json.dumps(entry) + "\n")

def get_log():
    try:
        with open(config.LOG_FILE) as f:
            return [json.loads(line) for line in f]
    except FileNotFoundError:
        return []


@app.route("/log", methods=["GET"])
def read_log():
    return jsonify({"entries": get_log()})

if __name__ == "__main__":
    app.run(port=5000, debug=True)
